In [1]:
!pip install pyyaml

Collecting pyyaml
  Downloading PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
Downloading PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)
   ---------------------------------------- 0.0/156.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/156.3 kB ? eta -:--:--
   -- ------------------------------------- 10.2/156.3 kB ? eta -:--:--
   -- ------------------------------------- 10.2/156.3 kB ? eta -:--:--
   ---------- ---------------------------- 41.0/156.3 kB 326.8 kB/s eta 0:00:01
   ---------------------------------------  153.6/156.3 kB 1.0 MB/s eta 0:00:01
   -------------------------------------- 156.3/156.3 kB 936.5 kB/s eta 0:00:00
Installing collected packages: pyyaml
Successfully installed pyyaml-6.0.2

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd
import yaml
import glob

folders_path = r"C:\Users\ajith\GUVI_AI_ML\PROJECTS\STOCK_ANALYSIS\Data\data"
folder_pattern = f"{folders_path}\*"
all_folders = glob.glob(folder_pattern)
stock_combined_df = pd.DataFrame()

for folder in all_folders:

    file_pattern = f"{folder}\*.yaml"
    all_files = glob.glob(file_pattern)
    
    for curr_file in all_files:
        with open(curr_file, 'r') as file:
            yaml_data = yaml.safe_load(file)
        df = pd.DataFrame(yaml_data)
        stock_combined_df = pd.concat([stock_combined_df, df])

stock_combined_df

<>:6: SyntaxWarning: invalid escape sequence '\*'
<>:12: SyntaxWarning: invalid escape sequence '\*'
<>:6: SyntaxWarning: invalid escape sequence '\*'
<>:12: SyntaxWarning: invalid escape sequence '\*'
C:\Users\ajith\AppData\Local\Temp\ipykernel_13792\3419329139.py:6: SyntaxWarning: invalid escape sequence '\*'
  folder_pattern = f"{folders_path}\*"
C:\Users\ajith\AppData\Local\Temp\ipykernel_13792\3419329139.py:12: SyntaxWarning: invalid escape sequence '\*'
  file_pattern = f"{folder}\*.yaml"

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
45,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
46,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
47,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
48,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
49,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [8]:
unique_stocks = stock_combined_df['Ticker'].unique()
path = r"C:\Users\ajith\GUVI_AI_ML\PROJECTS\STOCK_ANALYSIS\Data\stocks_csv"
for stock in unique_stocks:
    unique_stock_df = stock_combined_df[stock_combined_df['Ticker'] == stock]
    unique_stock_df.to_csv(f"{path}\{stock}.csv", index=False)

<string>:5: SyntaxWarning: invalid escape sequence '\{'
<>:5: SyntaxWarning: invalid escape sequence '\{'
<string>:5: SyntaxWarning: invalid escape sequence '\{'
<>:5: SyntaxWarning: invalid escape sequence '\{'
C:\Users\ajith\AppData\Local\Temp\ipykernel_13792\2024968304.py:5: SyntaxWarning: invalid escape sequence '\{'
  unique_stock_df.to_csv(f"{path}\{stock}.csv", index=False)

In [10]:
!pip uninstall mysql
!pip install mysql-connector-python

WARNING: Skipping mysql as it is not installed.

Requirement already satisfied: mysql-connector-python in c:\users\ajith\appdata\local\programs\python\python312\lib\site-packages (9.3.0)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
import mysql.connector


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678"
)
cursor = connection.cursor()

query = "create database stocks_db"
cursor.execute(query)

DatabaseError: 1007 (HY000): Can't create database 'stocks_db'; database exists

In [45]:
query = "show databases"
cursor.execute(query)
for db in cursor:
    print(db)

('imdb',)
('information_schema',)
('mysql',)
('performance_schema',)
('stocks_db',)
('sys',)

In [46]:
query = "use stocks_db"
cursor.execute(query)

In [ ]:
stock_combined_df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
45,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
46,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
47,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
48,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
49,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [15]:
query = "create table stock_exchange_details(ticker varchar(100), close float, date datetime, high float, low float, month date, open float, volume int)"
cursor.execute(query)

In [16]:
query = "desc stock_exchange_details"
cursor.execute(query)
for item in cursor:
    print(item)

('ticker', 'varchar(100)', 'YES', '', None, '')
('close', 'float', 'YES', '', None, '')
('date', 'datetime', 'YES', '', None, '')
('high', 'float', 'YES', '', None, '')
('low', 'float', 'YES', '', None, '')
('month', 'date', 'YES', '', None, '')
('open', 'float', 'YES', '', None, '')
('volume', 'int', 'YES', '', None, '')

In [ ]:
stock_combined_df.reset_index(drop=True, inplace=True)
stock_combined_df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
14195,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
14196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
14197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
14198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
14199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [57]:
from datetime import datetime, date

data = []
for index in stock_combined_df.index:
    row = stock_combined_df.loc[index].values
    row[0] = str(row[0])
    row[1] = float(row[1])
    row[2] = datetime.strptime(row[2], '%Y-%m-%d %H:%M:%S')
    row[3] = float(row[3])
    row[4] = float(row[4])
    year_month = row[5].split('-')
    formattted_month = date(int(year_month[0]),int(year_month[1]),1)
    row[5] = formattted_month
    row[6] = float(row[6])
    row[7] = int(row[7])
    data.append(tuple(row))

query = "insert into stock_exchange_details values(%s,%s,%s,%s,%s,%s,%s,%s)"
cursor.executemany(query,data)
connection.commit()

InternalError: Unread result found

In [58]:
query = "select * from stock_exchange_details"
cursor.execute(query)

for i in cursor:
    print(i)

InternalError: Unread result found

In [40]:
stock_combined_df

,Ticker,close,date,high,low,month,open,volume
0,SBIN,602.95,2023-10-03 05:30:00,604.9,589.60,2023-10,596.60,15322196
1,BAJFINANCE,7967.60,2023-10-03 05:30:00,7975.5,7755.00,2023-10,7780.80,944555
2,TITAN,3196.25,2023-10-03 05:30:00,3212.5,3114.40,2023-10,3148.80,1007308
3,ITC,439.75,2023-10-03 05:30:00,442.9,439.25,2023-10,441.00,7481883
4,TCS,3513.85,2023-10-03 05:30:00,3534.2,3480.10,2023-10,3534.20,1948148
...,...,...,...,...,...,...,...,...
14195,HINDALCO,652.10,2024-11-22 05:30:00,657.3,647.40,2024-11,652.95,3586402
14196,HEROMOTOCO,4794.10,2024-11-22 05:30:00,4808.4,4742.00,2024-11,4778.40,394712
14197,AXISBANK,1142.40,2024-11-22 05:30:00,1147.9,1127.55,2024-11,1136.65,16687505
14198,HDFCBANK,1745.60,2024-11-22 05:30:00,1754.3,1729.55,2024-11,1743.55,12386806
14199,BAJAJ-AUTO,9481.65,2024-11-22 05:30:00,9602.9,9444.10,2024-11,9545.00,619823

In [60]:

import mysql.connector


connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678"
)
cursor = connection.cursor()

query = "use stocks_db"
cursor.execute(query)

query = "select * from stock_exchange_details"
query = "select * from stock_exchange_details"
cursor.execute(query)

for i in cursor:
    print(i)

('SBIN', 602.95, datetime.datetime(2023, 10, 3, 5, 30), 604.9, 589.6, datetime.date(2023, 10, 1), 596.6, 15322196)
('BAJFINANCE', 7967.6, datetime.datetime(2023, 10, 3, 5, 30), 7975.5, 7755.0, datetime.date(2023, 10, 1), 7780.8, 944555)
('TITAN', 3196.25, datetime.datetime(2023, 10, 3, 5, 30), 3212.5, 3114.4, datetime.date(2023, 10, 1), 3148.8, 1007308)
('ITC', 439.75, datetime.datetime(2023, 10, 3, 5, 30), 442.9, 439.25, datetime.date(2023, 10, 1), 441.0, 7481883)
('TCS', 3513.85, datetime.datetime(2023, 10, 3, 5, 30), 3534.2, 3480.1, datetime.date(2023, 10, 1), 3534.2, 1948148)
('LT', 3073.25, datetime.datetime(2023, 10, 3, 5, 30), 3077.45, 2995.1, datetime.date(2023, 10, 1), 3040.5, 3254492)
('TATACONSUM', 861.2, datetime.datetime(2023, 10, 3, 5, 30), 868.75, 853.49, datetime.date(2023, 10, 1), 859.32, 1168848)
('RELIANCE', 1159.08, datetime.datetime(2023, 10, 3, 5, 30), 1167.8, 1158.0, datetime.date(2023, 10, 1), 1164.97, 8859056)
('HCLTECH', 1238.7, datetime.datetime(2023, 10, 3, 5, 30), 1256.7, 1222.7, datetime.date(2023, 10, 1), 1232.5, 2162636)
('JSWSTEEL', 770.25, datetime.datetime(2023, 10, 3, 5, 30), 776.55, 768.0, datetime.date(2023, 10, 1), 776.55, 1099773)
('ULTRACEMCO', 8304.9, datetime.datetime(2023, 10, 3, 5, 30), 8377.0, 8221.2, datetime.date(2023, 10, 1), 8289.0, 454402)
('POWERGRID', 199.55, datetime.datetime(2023, 10, 3, 5, 30), 200.0, 196.9, datetime.date(2023, 10, 1), 198.75, 10830728)
('INFY', 1434.0, datetime.datetime(2023, 10, 3, 5, 30), 1437.0, 1420.3, datetime.date(2023, 10, 1), 1436.05, 4181867)
('TRENT', 2059.1, datetime.datetime(2023, 10, 3, 5, 30), 2086.3, 2052.0, datetime.date(2023, 10, 1), 2074.3, 543387)
('BHARTIARTL', 925.3, datetime.datetime(2023, 10, 3, 5, 30), 928.25, 916.05, datetime.date(2023, 10, 1), 918.25, 4338272)
('TATAMOTORS', 620.45, datetime.datetime(2023, 10, 3, 5, 30), 632.65, 618.6, datetime.date(2023, 10, 1), 632.6, 6894577)
('WIPRO', 405.45, datetime.datetime(2023, 10, 3, 5, 30), 408.1, 403.6, datetime.date(2023, 10, 1), 406.45, 2864052)
('TECHM', 1216.2, datetime.datetime(2023, 10, 3, 5, 30), 1230.7, 1212.55, datetime.date(2023, 10, 1), 1220.6, 1622290)
('NTPC', 241.2, datetime.datetime(2023, 10, 3, 5, 30), 246.7, 240.55, datetime.date(2023, 10, 1), 244.35, 14885044)
('HINDUNILVR', 2468.9, datetime.datetime(2023, 10, 3, 5, 30), 2499.0, 2461.8, datetime.date(2023, 10, 1), 2490.0, 1585626)
('APOLLOHOSP', 5118.95, datetime.datetime(2023, 10, 3, 5, 30), 5154.95, 5066.0, datetime.date(2023, 10, 1), 5138.95, 268482)
('M&M', 1537.4, datetime.datetime(2023, 10, 3, 5, 30), 1598.0, 1533.05, datetime.date(2023, 10, 1), 1597.2, 3436776)
('GRASIM', 1913.84, datetime.datetime(2023, 10, 3, 5, 30), 1931.32, 1899.1, datetime.date(2023, 10, 1), 1920.46, 591326)
('ICICIBANK', 940.3, datetime.datetime(2023, 10, 3, 5, 30), 951.6, 939.0, datetime.date(2023, 10, 1), 951.6, 11131636)
('ADANIENT', 2387.25, datetime.datetime(2023, 10, 3, 5, 30), 2424.9, 2372.0, datetime.date(2023, 10, 1), 2418.0, 2019899)
('ADANIPORTS', 831.4, datetime.datetime(2023, 10, 3, 5, 30), 836.75, 824.25, datetime.date(2023, 10, 1), 826.0, 2453090)
('BEL', 139.2, datetime.datetime(2023, 10, 3, 5, 30), 140.6, 137.2, datetime.date(2023, 10, 1), 137.9, 19010910)
('BAJAJFINSV', 1561.05, datetime.datetime(2023, 10, 3, 5, 30), 1564.2, 1527.0, datetime.date(2023, 10, 1), 1530.25, 1083086)
('EICHERMOT', 3351.4, datetime.datetime(2023, 10, 3, 5, 30), 3434.95, 3302.9, datetime.date(2023, 10, 1), 3426.9, 1354075)
('COALINDIA', 291.9, datetime.datetime(2023, 10, 3, 5, 30), 297.1, 290.1, datetime.date(2023, 10, 1), 297.05, 9348540)
('MARUTI', 10346.9, datetime.datetime(2023, 10, 3, 5, 30), 10709.8, 10303.3, datetime.date(2023, 10, 1), 10709.8, 623006)
('INDUSINDBK', 1435.4, datetime.datetime(2023, 10, 3, 5, 30), 1438.4, 1420.0, datetime.date(2023, 10, 1), 1432.0, 1442499)
('ASIANPAINT', 3166.85, datetime.datetime(2023, 10, 3, 5, 30), 3227.8, 3162.0, datetime.date(2023, 10, 1), 3166.1, 1219145)
('TATASTEEL', 128.0, datetime.datetime(2023, 10, 3, 5, 30), 129.1, 127.25, datetime.date(2023, 10, 1), 129.0, 18613557)
('HDFCLIFE', 633.55, datetime.datetime(2023, 10, 3, 5, 30), 637.5, 628.55, datetime.date(2023, 10, 1), 634.45, 3454441)
('DRREDDY', 1092.34, datetime.datetime(2023, 10, 3, 5, 30), 1117.38, 1090.0, datetime.date(2023, 10, 1), 1117.38, 2065240)
('SUNPHARMA', 1141.45, datetime.datetime(2023, 10, 3, 5, 30), 1161.95, 1139.25, datetime.date(2023, 10, 1), 1159.55, 1946966)
('KOTAKBANK', 1727.05, datetime.datetime(2023, 10, 3, 5, 30), 1735.0, 1715.45, datetime.date(2023, 10, 1), 1730.0, 5534869)
('SHRIRAMFIN', 1921.95, datetime.datetime(2023, 10, 3, 5, 30), 1939.9, 1881.0, datetime.date(2023, 10, 1), 1938.0, 2207907)
('NESTLEIND', 2231.52, datetime.datetime(2023, 10, 3, 5, 30), 2259.47, 2225.52, datetime.date(2023, 10, 1), 2250.69, 500130)
('ONGC', 184.6, datetime.datetime(2023, 10, 3, 5, 30), 189.3, 183.65, datetime.date(2023, 10, 1), 189.3, 22118500)
('CIPLA', 1182.8, datetime.datetime(2023, 10, 3, 5, 30), 1185.7, 1170.95, datetime.date(2023, 10, 1), 1184.0, 1581125)
('BPCL', 170.68, datetime.datetime(2023, 10, 3, 5, 30), 174.6, 170.43, datetime.date(2023, 10, 1), 174.25, 10514554)
('BRITANNIA', 4495.45, datetime.datetime(2023, 10, 3, 5, 30), 4553.25, 4486.6, datetime.date(2023, 10, 1), 4524.8, 543482)
('SBILIFE', 1292.45, datetime.datetime(2023, 10, 3, 5, 30), 1302.15, 1282.65, datetime.date(2023, 10, 1), 1302.15, 1282289)
('HINDALCO', 479.95, datetime.datetime(2023, 10, 3, 5, 30), 484.55, 476.6, datetime.date(2023, 10, 1), 483.1, 4657602)
('HEROMOTOCO', 3015.6, datetime.datetime(2023, 10, 3, 5, 30), 3064.9, 2991.5, datetime.date(2023, 10, 1), 3058.0, 387906)
('AXISBANK', 1041.05, datetime.datetime(2023, 10, 3, 5, 30), 1044.7, 1032.6, datetime.date(2023, 10, 1), 1035.0, 11589322)
('HDFCBANK', 1508.05, datetime.datetime(2023, 10, 3, 5, 30), 1527.0, 1506.0, datetime.date(2023, 10, 1), 1527.0, 19485847)
('BAJAJ-AUTO', 5016.45, datetime.datetime(2023, 10, 3, 5, 30), 5073.0, 4997.1, datetime.date(2023, 10, 1), 5065.0, 464531)
('SBIN', 586.25, datetime.datetime(2023, 10, 4, 5, 30), 600.45, 584.45, datetime.date(2023, 10, 1), 600.0, 24914612)
('BAJFINANCE', 7854.05, datetime.datetime(2023, 10, 4, 5, 30), 8043.0, 7820.0, datetime.date(2023, 10, 1), 8025.0, 1176384)
('TITAN', 3166.65, datetime.datetime(2023, 10, 4, 5, 30), 3205.0, 3151.0, datetime.date(2023, 10, 1), 3186.0, 486969)
('ITC', 436.1, datetime.datetime(2023, 10, 4, 5, 30), 441.7, 433.3, datetime.date(2023, 10, 1), 439.75, 13396709)
('TCS', 3537.75, datetime.datetime(2023, 10, 4, 5, 30), 3548.0, 3477.3, datetime.date(2023, 10, 1), 3486.3, 1788138)
('LT', 3027.75, datetime.datetime(2023, 10, 4, 5, 30), 3064.1, 2990.05, datetime.date(2023, 10, 1), 3064.1, 3100946)
('TATACONSUM', 854.13, datetime.datetime(2023, 10, 4, 5, 30), 859.17, 844.5, datetime.date(2023, 10, 1), 856.36, 615431)
('RELIANCE', 1157.08, datetime.datetime(2023, 10, 4, 5, 30), 1159.5, 1147.55, datetime.date(2023, 10, 1), 1154.5, 10286386)
('HCLTECH', 1239.55, datetime.datetime(2023, 10, 4, 5, 30), 1244.8, 1225.0, datetime.date(2023, 10, 1), 1234.0, 2253785)
('JSWSTEEL', 756.6, datetime.datetime(2023, 10, 4, 5, 30), 768.0, 753.15, datetime.date(2023, 10, 1), 767.95, 1654158)
('ULTRACEMCO', 8120.85, datetime.datetime(2023, 10, 4, 5, 30), 8292.55, 8045.05, datetime.date(2023, 10, 1), 8292.55, 884369)
('POWERGRID', 199.0, datetime.datetime(2023, 10, 4, 5, 30), 199.4, 195.4, datetime.date(2023, 10, 1), 198.9, 14120040)
('INFY', 1444.35, datetime.datetime(2023, 10, 4, 5, 30), 1449.95, 1418.2, datetime.date(2023, 10, 1), 1425.0, 4510406)
('TRENT', 2022.3, datetime.datetime(2023, 10, 4, 5, 30), 2055.95, 2007.6, datetime.date(2023, 10, 1), 2054.0, 551771)
('BHARTIARTL', 924.25, datetime.datetime(2023, 10, 4, 5, 30), 925.95, 918.3, datetime.date(2023, 10, 1), 918.3, 5603669)
('TATAMOTORS', 613.6, datetime.datetime(2023, 10, 4, 5, 30), 620.8, 608.3, datetime.date(2023, 10, 1), 620.8, 7612709)
('WIPRO', 404.9, datetime.datetime(2023, 10, 4, 5, 30), 405.45, 400.65, datetime.date(2023, 10, 1), 402.7, 3452935)
('TECHM', 1205.0, datetime.datetime(2023, 10, 4, 5, 30), 1215.5, 1186.05, datetime.date(2023, 10, 1), 1210.0, 2340603)
('NTPC', 235.15, datetime.datetime(2023, 10, 4, 5, 30), 241.0, 231.5, datetime.date(2023, 10, 1), 241.0, 25424437)
('HINDUNILVR', 2507.85, datetime.datetime(2023, 10, 4, 5, 30), 2511.05, 2465.15, datetime.date(2023, 10, 1), 2467.05, 1587335)
('APOLLOHOSP', 5047.4, datetime.datetime(2023, 10, 4, 5, 30), 5096.85, 4982.3, datetime.date(2023, 10, 1), 5085.0, 442482)
('M&M', 1522.1, datetime.datetime(2023, 10, 4, 5, 30), 1537.9, 1501.75, datetime.date(2023, 10, 1), 1531.8, 2580901)
('GRASIM', 1888.34, datetime.datetime(2023, 10, 4, 5, 30), 1902.44, 1869.62, datetime.date(2023, 10, 1), 1898.45, 687673)
('ICICIBANK', 930.05, datetime.datetime(2023, 10, 4, 5, 30), 935.5, 925.0, datetime.date(2023, 10, 1), 935.0, 17334739)
('ADANIENT', 2464.95, datetime.datetime(2023, 10, 4, 5, 30), 2502.75, 2392.25, datetime.date(2023, 10, 1), 2402.2, 2857377)
('ADANIPORTS', 824.6, datetime.datetime(2023, 10, 4, 5, 30), 845.45, 819.35, datetime.date(2023, 10, 1), 830.95, 4096647)
('BEL', 138.85, datetime.datetime(2023, 10, 4, 5, 30), 139.15, 136.55, datetime.date(2023, 10, 1), 138.0, 14912053)
('BAJAJFINSV', 1532.55, datetime.datetime(2023, 10, 4, 5, 30), 1555.85, 1521.15, datetime.date(2023, 10, 1), 1555.0, 1614123)
('EICHERMOT', 3400.9, datetime.datetime(2023, 10, 4, 5, 30), 3408.95, 3323.75, datetime.date(2023, 10, 1), 3350.0, 566983)
('COALINDIA', 287.95, datetime.datetime(2023, 10, 4, 5, 30), 291.5, 285.9, datetime.date(2023, 10, 1), 290.8, 6338888)
('MARUTI', 10129.8, datetime.datetime(2023, 10, 4, 5, 30), 10283.9, 10090.0, datetime.date(2023, 10, 1), 10283.9, 407793)
('INDUSINDBK', 1401.3, datetime.datetime(2023, 10, 4, 5, 30), 1428.5, 1386.2, datetime.date(2023, 10, 1), 1424.85, 3978667)
('ASIANPAINT', 3169.9, datetime.datetime(2023, 10, 4, 5, 30), 3189.0, 3151.35, datetime.date(2023, 10, 1), 3164.95, 892584)
('TATASTEEL', 125.3, datetime.datetime(2023, 10, 4, 5, 30), 127.1, 124.5, datetime.date(2023, 10, 1), 127.0, 33272725)
('HDFCLIFE', 625.5, datetime.datetime(2023, 10, 4, 5, 30), 632.0, 624.25, datetime.date(2023, 10, 1), 631.0, 2357914)
('DRREDDY', 1083.56, datetime.datetime(2023, 10, 4, 5, 30), 1099.8, 1080.3, datetime.date(2023, 10, 1), 1093.0, 2109530)
('SUNPHARMA', 1123.8, datetime.datetime(2023, 10, 4, 5, 30), 1139.0, 1113.0, datetime.date(2023, 10, 1), 1138.1, 1803871)
('KOTAKBANK', 1722.05, datetime.datetime(2023, 10, 4, 5, 30), 1727.0, 1709.0, datetime.date(2023, 10, 1), 1715.0, 6220979)
('SHRIRAMFIN', 1850.6, datetime.datetime(2023, 10, 4, 5, 30), 1919.95, 1841.5, datetime.date(2023, 10, 1), 1909.0, 1340167)
('NESTLEIND', 2298.62, datetime.datetime(2023, 10, 4, 5, 30), 2335.88, 2255.1, datetime.date(2023, 10, 1), 2280.51, 2134880)
('ONGC', 182.75, datetime.datetime(2023, 10, 4, 5, 30), 184.6, 182.1, datetime.date(2023, 10, 1), 184.45, 9360058)
('CIPLA', 1167.05, datetime.datetime(2023, 10, 4, 5, 30), 1185.0, 1161.3, datetime.date(2023, 10, 1), 1178.1, 999123)
('BPCL', 170.68, datetime.datetime(2023, 10, 4, 5, 30), 172.48, 169.78, datetime.date(2023, 10, 1), 170.68, 6049760)
('BRITANNIA', 4532.5, datetime.datetime(2023, 10, 4, 5, 30), 4540.0, 4466.75, datetime.date(2023, 10, 1), 4490.0, 318564)
('SBILIFE', 1270.55, datetime.datetime(2023, 10, 4, 5, 30), 1297.7, 1264.35, datetime.date(2023, 10, 1), 1291.6, 1139615)
('HINDALCO', 473.4, datetime.datetime(2023, 10, 4, 5, 30), 477.9, 470.0, datetime.date(2023, 10, 1), 474.0, 3302259)
('HEROMOTOCO', 2989.05, datetime.datetime(2023, 10, 4, 5, 30), 3020.0, 2976.05, datetime.date(2023, 10, 1), 3015.95, 307263)
('AXISBANK', 995.55, datetime.datetime(2023, 10, 4, 5, 30), 1037.0, 988.85, datetime.date(2023, 10, 1), 1035.35, 22584212)
('HDFCBANK', 1529.55, datetime.datetime(2023, 10, 4, 5, 30), 1535.0, 1489.25, datetime.date(2023, 10, 1), 1495.0, 27324715)
('BAJAJ-AUTO', 4918.6, datetime.datetime(2023, 10, 4, 5, 30), 5019.2, 4903.05, datetime.date(2023, 10, 1), 5011.25, 256544)
('SBIN', 592.15, datetime.datetime(2023, 10, 5, 5, 30), 594.35, 587.1, datetime.date(2023, 10, 1), 590.0, 13248028)
('BAJFINANCE', 7850.9, datetime.datetime(2023, 10, 5, 5, 30), 7914.85, 7826.9, datetime.date(2023, 10, 1), 7914.85, 795061)
('TITAN', 3216.5, datetime.datetime(2023, 10, 5, 5, 30), 3231.0, 3165.0, datetime.date(2023, 10, 1), 3173.9, 1109881)
('ITC', 436.05, datetime.datetime(2023, 10, 5, 5, 30), 440.5, 435.05, datetime.date(2023, 10, 1), 440.0, 10030257)
('TCS', 3589.35, datetime.datetime(2023, 10, 5, 5, 30), 3624.0, 3551.2, datetime.date(2023, 10, 1), 3554.0, 2990768)
('LT', 3096.05, datetime.datetime(2023, 10, 5, 5, 30), 3114.9, 3032.55, datetime.date(2023, 10, 1), 3032.55, 3413447)
('TATACONSUM', 849.64, datetime.datetime(2023, 10, 5, 5, 30), 858.58, 846.97, datetime.date(2023, 10, 1), 855.42, 740770)
('RELIANCE', 1157.05, datetime.datetime(2023, 10, 5, 5, 30), 1164.7, 1154.5, datetime.date(2023, 10, 1), 1159.63, 10953682)
('HCLTECH', 1235.45, datetime.datetime(2023, 10, 5, 5, 30), 1253.95, 1227.8, datetime.date(2023, 10, 1), 1249.0, 2995200)
('JSWSTEEL', 755.5, datetime.datetime(2023, 10, 5, 5, 30), 762.65, 752.9, datetime.date(2023, 10, 1), 762.0, 1459736)
('ULTRACEMCO', 8177.45, datetime.datetime(2023, 10, 5, 5, 30), 8208.8, 8125.0, datetime.date(2023, 10, 1), 8177.0, 310506)
('POWERGRID', 196.6, datetime.datetime(2023, 10, 5, 5, 30), 199.5, 195.35, datetime.date(2023, 10, 1), 199.5, 14575590)
('INFY', 1463.45, datetime.datetime(2023, 10, 5, 5, 30), 1475.65, 1450.2, datetime.date(2023, 10, 1), 1452.0, 7384621)
('TRENT', 2047.6, datetime.datetime(2023, 10, 5, 5, 30), 2058.15, 2022.3, datetime.date(2023, 10, 1), 2022.95, 461744)
('BHARTIARTL', 928.85, datetime.datetime(2023, 10, 5, 5, 30), 929.6, 919.4, datetime.date(2023, 10, 1), 925.05, 7063132)
('TATAMOTORS', 619.6, datetime.datetime(2023, 10, 5, 5, 30), 621.35, 614.65, datetime.date(2023, 10, 1), 619.0, 7893892)
('WIPRO', 406.8, datetime.datetime(2023, 10, 5, 5, 30), 410.4, 405.0, datetime.date(2023, 10, 1), 407.95, 4062652)
('TECHM', 1205.6, datetime.datetime(2023, 10, 5, 5, 30), 1223.95, 1199.5, datetime.date(2023, 10, 1), 1214.0, 2497613)
('NTPC', 233.85, datetime.datetime(2023, 10, 5, 5, 30), 237.4, 232.05, datetime.date(2023, 10, 1), 237.25, 22472389)
('HINDUNILVR', 2519.55, datetime.datetime(2023, 10, 5, 5, 30), 2524.8, 2495.35, datetime.date(2023, 10, 1), 2518.0, 1909928)
('APOLLOHOSP', 5047.05, datetime.datetime(2023, 10, 5, 5, 30), 5079.85, 5026.65, datetime.date(2023, 10, 1), 5054.95, 363289)
('M&M', 1537.95, datetime.datetime(2023, 10, 5, 5, 30), 1550.8, 1513.05, datetime.date(2023, 10, 1), 1533.0, 1991367)
('GRASIM', 1882.67, datetime.datetime(2023, 10, 5, 5, 30), 1901.44, 1873.55, datetime.date(2023, 10, 1), 1889.59, 544715)
('ICICIBANK', 940.85, datetime.datetime(2023, 10, 5, 5, 30), 943.95, 934.55, datetime.date(2023, 10, 1), 935.2, 10478856)
('ADANIENT', 2466.35, datetime.datetime(2023, 10, 5, 5, 30), 2486.5, 2446.4, datetime.date(2023, 10, 1), 2477.95, 1132455)
('ADANIPORTS', 825.2, datetime.datetime(2023, 10, 5, 5, 30), 832.0, 820.25, datetime.date(2023, 10, 1), 830.85, 2083505)
('BEL', 138.95, datetime.datetime(2023, 10, 5, 5, 30), 141.35, 138.1, datetime.date(2023, 10, 1), 139.5, 15996620)
('BAJAJFINSV', 1542.55, datetime.datetime(2023, 10, 5, 5, 30), 1556.0, 1532.3, datetime.date(2023, 10, 1), 1540.0, 1153064)
('EICHERMOT', 3443.6, datetime.datetime(2023, 10, 5, 5, 30), 3453.9, 3387.05, datetime.date(2023, 10, 1), 3405.5, 394665)
('COALINDIA', 289.35, datetime.datetime(2023, 10, 5, 5, 30), 290.55, 283.9, datetime.date(2023, 10, 1), 288.8, 8687014)
('MARUTI', 10210.2, datetime.datetime(2023, 10, 5, 5, 30), 10271.0, 10109.0, datetime.date(2023, 10, 1), 10182.0, 377196)
('INDUSINDBK', 1401.85, datetime.datetime(2023, 10, 5, 5, 30), 1415.4, 1394.3, datetime.date(2023, 10, 1), 1408.7, 1647175)
('ASIANPAINT', 3206.25, datetime.datetime(2023, 10, 5, 5, 30), 3232.1, 3174.3, datetime.date(2023, 10, 1), 3210.0, 1002610)
('TATASTEEL', 125.25, datetime.datetime(2023, 10, 5, 5, 30), 126.15, 124.55, datetime.date(2023, 10, 1), 125.9, 27063441)
('HDFCLIFE', 624.35, datetime.datetime(2023, 10, 5, 5, 30), 627.75, 619.9, datetime.date(2023, 10, 1), 626.0, 4050085)
('DRREDDY', 1081.45, datetime.datetime(2023, 10, 5, 5, 30), 1095.0, 1080.0, datetime.date(2023, 10, 1), 1092.0, 2058530)
('SUNPHARMA', 1119.1, datetime.datetime(2023, 10, 5, 5, 30), 1128.65, 1111.8, datetime.date(2023, 10, 1), 1124.65, 2348562)
('KOTAKBANK', 1734.25, datetime.datetime(2023, 10, 5, 5, 30), 1747.0, 1721.15, datetime.date(2023, 10, 1), 1730.0, 2966801)
('SHRIRAMFIN', 1837.5, datetime.datetime(2023, 10, 5, 5, 30), 1872.95, 1823.0, datetime.date(2023, 10, 1), 1852.0, 1479477)
('NESTLEIND', 2291.87, datetime.datetime(2023, 10, 5, 5, 30), 2310.72, 2277.5, datetime.date(2023, 10, 1), 2300.5, 680000)
('ONGC', 182.2, datetime.datetime(2023, 10, 5, 5, 30), 184.0, 181.0, datetime.date(2023, 10, 1), 181.25, 11128340)
('CIPLA', 1161.1, datetime.datetime(2023, 10, 5, 5, 30), 1172.95, 1155.25, datetime.date(2023, 10, 1), 1170.1, 1446743)
('BPCL', 172.23, datetime.datetime(2023, 10, 5, 5, 30), 173.88, 171.4, datetime.date(2023, 10, 1), 172.75, 7115506)
('BRITANNIA', 4533.9, datetime.datetime(2023, 10, 5, 5, 30), 4548.2, 4500.0, datetime.date(2023, 10, 1), 4540.25, 302015)
('SBILIFE', 1274.45, datetime.datetime(2023, 10, 5, 5, 30), 1282.1, 1264.95, datetime.date(2023, 10, 1), 1271.0, 979561)
('HINDALCO', 470.55, datetime.datetime(2023, 10, 5, 5, 30), 482.4, 468.35, datetime.date(2023, 10, 1), 473.4, 4801287)
('HEROMOTOCO', 3016.65, datetime.datetime(2023, 10, 5, 5, 30), 3048.85, 2993.4, datetime.date(2023, 10, 1), 3020.0, 537209)
('AXISBANK', 1003.25, datetime.datetime(2023, 10, 5, 5, 30), 1009.2, 988.9, datetime.date(2023, 10, 1), 1000.0, 7950412)
('HDFCBANK', 1535.75, datetime.datetime(2023, 10, 5, 5, 30), 1551.55, 1532.6, datetime.date(2023, 10, 1), 1535.05, 24256337)
('BAJAJ-AUTO', 5011.05, datetime.datetime(2023, 10, 5, 5, 30), 5039.3, 4925.1, datetime.date(2023, 10, 1), 4935.0, 657876)
('SBIN', 594.25, datetime.datetime(2023, 10, 6, 5, 30), 598.95, 592.2, datetime.date(2023, 10, 1), 593.4, 8216780)
('BAJFINANCE', 8168.55, datetime.datetime(2023, 10, 6, 5, 30), 8192.0, 7845.0, datetime.date(2023, 10, 1), 7850.0, 2145034)
('TITAN', 3309.75, datetime.datetime(2023, 10, 6, 5, 30), 3319.8, 3221.1, datetime.date(2023, 10, 1), 3230.0, 1102120)
('ITC', 442.15, datetime.datetime(2023, 10, 6, 5, 30), 443.6, 436.65, datetime.date(2023, 10, 1), 437.85, 8418580)
('TCS', 3621.4, datetime.datetime(2023, 10, 6, 5, 30), 3634.95, 3575.05, datetime.date(2023, 10, 1), 3591.0, 2075691)
('LT', 3093.7, datetime.datetime(2023, 10, 6, 5, 30), 3114.95, 3073.15, datetime.date(2023, 10, 1), 3114.95, 1898118)
('TATACONSUM', 864.01, datetime.datetime(2023, 10, 6, 5, 30), 866.73, 850.43, datetime.date(2023, 10, 1), 850.43, 948330)
('RELIANCE', 1159.0, datetime.datetime(2023, 10, 6, 5, 30), 1162.4, 1156.03, datetime.date(2023, 10, 1), 1158.53, 5431026)
('HCLTECH', 1237.7, datetime.datetime(2023, 10, 6, 5, 30), 1256.0, 1230.1, datetime.date(2023, 10, 1), 1252.0, 2497711)
('JSWSTEEL', 765.2, datetime.datetime(2023, 10, 6, 5, 30), 771.15, 758.65, datetime.date(2023, 10, 1), 760.35, 2026927)
('ULTRACEMCO', 8195.45, datetime.datetime(2023, 10, 6, 5, 30), 8239.65, 8151.25, datetime.date(2023, 10, 1), 8198.0, 158491)
('POWERGRID', 197.05, datetime.datetime(2023, 10, 6, 5, 30), 197.45, 194.85, datetime.date(2023, 10, 1), 197.0, 12857229)
('INFY', 1478.7, datetime.datetime(2023, 10, 6, 5, 30), 1484.5, 1463.3, datetime.date(2023, 10, 1), 1469.5, 3598672)
('TRENT', 2072.1, datetime.datetime(2023, 10, 6, 5, 30), 2091.9, 2050.1, datetime.date(2023, 10, 1), 2055.85, 444220)
('BHARTIARTL', 926.05, datetime.datetime(2023, 10, 6, 5, 30), 929.2, 924.3, datetime.date(2023, 10, 1), 929.2, 2420855)